/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_com_Serial */

#ifndef _Included_com_example_com_Serial
#define _Included_com_example_com_Serial
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_com_example_com_Serial
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL Java_com_example_com_Serial_open
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_com_example_com_Serial
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_com_Serial_close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
